### ISSUE TITLE
Remove Facility

### ISSUE THREAD

**Issue by John-Almardeny** [TechLabCommunity/AFArray#7]
Have you thought about adding a `remove(int index)` option?

I know I can achieve it by slicing, but it would be more convenient though.

```
// Remove by index pseudo code
void remove(int index){
  AFArray<int> temp;
  for (int i=0; i<v1.size(); i++){
    if (i!=index){
      temp.add(v1[i]);
    }
  }
  v1 = temp;
}
```

**Comment by keyro90** [comment]
Yeah, you're right.
Initially I implemented slice method for the purpose.
I'm going to add it asap.
Thank you!
